title:  DiffBeautify
description: Fast Diffusion Model for High-Fidelity Singing Voice Beautifying with Pitch and Expressiveness Condition

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/DiffBeautifier/
